### ISSUE TITLE
Kuramoto Model with motion data

### ISSUE THREAD

**Issue by SutirthaChakraborty** [fabridamicelli/kuramoto#2]
Hi,
I have multiple 1D signals (motion signals), I want to find their phase and frequency and apply kuramoto's equation?

I would be glad you drop me a mail if you are interested  [email](sutirtha38@gmail.com) for more details,
Thanks, 
Suti

**Comment by fabridamicelli** [comment]
Hello @SutirthaChakraborty,
I'm not sure I understand your question and how I could be of any help. If you could elaborate a bit maybe I can say something more specific.
F

**Comment by SutirthaChakraborty** [comment]
Hi @fabridamicelli ,
I have average motion of each musicians extracted from [videos like this](https://www.youtube.com/watch?v=bPwA4gVobJ0&feature=emb_logo&ab_channel=BochenLi). I consider each human as an oscillator. I want a kuramoto's oscillator to match with their phase and oscillate. Does this make some sense ?
Sample code I am trying to do : [Colab link](https://colab.research.google.com/drive/1ESbD9OrojcIgrU07pgh1G0saLhCLyHY9?usp=sharing)

It is like I want an oscillator to match the rhythm of the other musician's body movement

Thanks,
Suti

**Comment by fabridamicelli** [comment]
Hi @SutirthaChakraborty,
That looks like an interesting project. 
Unfortunately I don't have the the time now to really look into the details in order to be able to help you more on the conceptual side.
But do let me know if you encounter any problems with the package itself so I can try to fix it :)
I am closing this but feel free to open another issue if problems pop up.
All the best,
F
