### ISSUE TITLE
faster running for simulation kuramoto model in network

### ISSUE THREAD

**Issue by MoJaNoohi** [fabridamicelli/kuramoto#4]
Hello ,
We utilize your kuramoto package in python for simulation kuramoto oscillators in a rectangular network.
The running time for simulation of a network in dimensions (1000,10) is approximately 5 hours. 
Please guide us on how we can reduce the running time to less than 1 hour for this dimension (1000,10)?!
Is it possible?

I send our code in a text  file.
[kuramoto model in complex network.txt](https://github.com/fabridamicelli/kuramoto/files/7663594/kuramoto.model.in.complex.network.txt)

**Comment by fabridamicelli** [comment]
Hi, 
I'll take a look at it and get back to you as soon as possible.
Best,
F

**Comment by MoJaNoohi** [comment]
Hello Dr.Damicelli ,
Thank you for your attention.


Sincerely,
MohammadJavad.

**Comment by MoJaNoohi** [comment]
Hello dr,
I hope to be well.

Do you look at my code?
I want to know your comment.

Sincerely.

**Comment by fabridamicelli** [comment]
I took a look at the code with your example. It seems like your graph size (10K nodes) is just too big for the underlying libraries (numpy and scipy). So I don't see any obvious solution. 

Having said that, maybe you could try to represent the adjacency matrix with int8 instead of float32 to save some space. But still I would not expect big improvement in the overall simulation speed.
I would try to play around a bit with smaller grids and profile the performance in order to gain some intuition about the scaling behaviour of the simulation time. And of course, I would ask myself first if I *really* need such grid size.
